#!/bin/bash

#--------------------------------------------------------------------------------------------------------------------------------
#SBATCH --job-name=nequip_train
#SBATCH --partition=gpumedium
#SBATCH --account=plantto # !!it is mandatory to specify the account (project) as precised in the CSC rules!!
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1 --cpus-per-task=72  # The product should be 72 if requesting 1 GPU per node
#SBATCH --mem-per-cpu=5G
#SBATCH --time=36:00:00
#SBATCH --gres=gpu:gh200:1  # Corresponds to 1 GPU per node
#SBATCH --output=ml_nequip-output_%j.txt
#SBATCH --error=ml_nequip-errors_%j.txt
#--------------------------------------------------------------------------------------------------------------------------------

# Record start time
start_time=$(date +"%Y-%m-%d %H:%M:%S")
echo "Job started at $start_time"

module load gcc/15.2.0
source /scratch/plantto/olaurila/allegro/allegro-venv/bin/activate

python -c "import torch; \
print(torch.__version__); \
print(torch.version.cuda); \
print(torch.cuda.is_available()); \
print(torch.cuda.device_count())"

# Set unlimited stack size
ulimit -s unlimited

nequip-train -cn config.yaml

# Record end time
end_time=$(date +"%Y-%m-%d %H:%M:%S")
echo "Job finished at $end_time"

# Calculate and print execution time
start_seconds=$(date -d "$start_time" +"%s")
end_seconds=$(date -d "$end_time" +"%s")
execution_time=$((end_seconds - start_seconds))
echo "Job took $execution_time seconds to complete."

exit 0
